# Generated by Django 3.1.4 on 2021-01-02 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=120)),
                ('task_description', models.CharField(max_length=1200)),
                ('dt_start', models.DateField()),
                ('dt_end', models.DateField()),
                ('emai', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ListItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('item_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_list.items')),
            ],
        ),
        migrations.DeleteModel(
            name='Itens',
        ),
    ]
